{
 "title": "UBFLIX",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "microservice",
    "query": {
     "query": "label_values(up{job!~\"prometheus\"}, job)"
    }
   },
   {
    "name": "endpoint",
    "query": {
     "query": "label_values(${microservice}_api_requests_total{endpoint!=\"/metrics\"}, endpoint)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Services", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Overview",
   "type": "stat",
   "description": "This provides a count of users and movies in DB.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) AS \"Movies\" FROM movies LIMIT 50 "
    },
    {
     "rawSql": "SELECT COUNT(*) AS \"Users\" FROM users LIMIT 50 "
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "stat",
   "description": "Cumulative number of requests since the service started.",
   "gridPos": { "h": 8, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(${microservice}_api_requests_total{endpoint=\"$endpoint\"})\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime Percentage",
   "type": "gauge",
   "description": "Availability of the service using \"up\" metric.",
   "gridPos": { "h": 8, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(up{job=~\"$microservice\"}[$__range]) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Model Satisfaction",
   "type": "timeseries",
   "description": "Provides the average feedback rating per model",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "movie_rating_sum_01 / movie_rating_count_01",
     "legendFormat": "Content Based Model"
    },
    {
     "expr": "movie_rating_sum_02 / movie_rating_count_02",
     "legendFormat": "Collaborative Model"
    },
    {
     "expr": "movie_rating_sum_03 / movie_rating_count_03",
     "legendFormat": "Popular Model"
    },
    {
     "expr": "(\r\n  (movie_rating_sum_01 + movie_rating_sum_02 + movie_rating_sum_03) /\r\n  (movie_rating_count_01 + movie_rating_count_02 + movie_rating_count_03)\r\n)\r\n",
     "legendFormat": "Hybrid Model"
    }
   ]
  },
  {
   "title": "Request Duration",
   "type": "timeseries",
   "description": "Request durations at the 50th, 90th, and 99th percentiles.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(${microservice}_api_request_latency_seconds_bucket{endpoint=\"$endpoint\"}[30s])) by (le))\r\n",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(${microservice}_api_request_latency_seconds_bucket{endpoint=\"$endpoint\"}[30s])) by (le))\r\n",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(${microservice}_api_request_latency_seconds_bucket{endpoint=\"$endpoint\"}[30s])) by (le))\r\n",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "Average Request Latency",
   "type": "timeseries",
   "description": "Average time taken to process a request.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "rate(${microservice}_api_request_latency_seconds_sum{endpoint=\"$endpoint\"}[30s]) /\r\nrate(${microservice}_api_request_latency_seconds_count{endpoint=\"$endpoint\"}[30s])\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Rate (RPS)",
   "type": "timeseries",
   "description": "Number of requests per second (RPS) handled by the service.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "rate(${microservice}_api_requests_total{endpoint=\"$endpoint\"}[30s])\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "95th Percentile Request Latency",
   "type": "heatmap",
   "description": "Latency under which 95% of requests are completed.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(${microservice}_api_request_latency_seconds_bucket{endpoint=\"$endpoint\"}[30s])) by (le))\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Storage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n    datname AS database_name,\r\n    pg_database_size(datname) AS db_size\r\nFROM pg_stat_database\r\nWHERE datname = 'postgresdb';"
    }
   ]
  },
  {
   "title": "Table Size Breakdown",
   "type": "barchart",
   "description": "Top 3 tables in storage size",
   "gridPos": { "h": 8, "w": 8, "x": 4, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "rawSql": "SELECT \r\n    relname AS table_name, \r\n    pg_total_relation_size(relid) AS total_size_bytes\r\nFROM pg_catalog.pg_statio_user_tables\r\nORDER BY total_size_bytes DESC\r\nLIMIT 3;\r\n"
    }
   ]
  },
  {
   "title": "Connection Metrics",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n    NOW() AS time, \r\n    COUNT(*) AS active_connections\r\nFROM pg_stat_activity;\r\n"
    }
   ]
  },
  {
   "title": "Cache Hit Ratio",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n    sum(heap_blks_hit) / nullif(sum(heap_blks_hit) + sum(heap_blks_read), 0) AS cache_hit_ratio\r\nFROM pg_statio_user_tables;\r\n"
    }
   ]
  },
  {
   "title": "Dead Tuples",
   "type": "piechart",
   "description": "Tables with the most dead tuples.\nRows that have been deleted/updated but not yet vacuumed",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n    relname AS \"table\",  -- Category (table name)\r\n    n_dead_tup AS \"dead_tuples\"  -- Value (number of dead tuples)\r\nFROM pg_stat_user_tables\r\nWHERE n_dead_tup > 0\r\nORDER BY n_dead_tup DESC\r\nLIMIT 10;\r\n"
    }
   ]
  },
  {
   "title": "Index Usage",
   "type": "table",
   "description": "index_scans: Number of times an index was used to retrieve data.\nsequential_scans: Number of times a full sequential scan was performed.",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 34 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    relname AS table_name, \r\n    idx_scan AS index_scans, \r\n    seq_scan AS sequential_scans\r\nFROM pg_stat_user_tables\r\nORDER BY idx_scan DESC\r\nLIMIT 10;\r\n"
    }
   ]
  },
  {
   "title": "Queries ",
   "type": "table",
   "description": "Long-Running Queries",
   "gridPos": { "h": 9, "w": 14, "x": 10, "y": 34 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    pid,\r\n    extract(epoch FROM age(clock_timestamp(), query_start)) AS duration_seconds,\r\n    state,\r\n    query,\r\n    clock_timestamp() AS timestamp\r\nFROM pg_stat_activity\r\nWHERE state != 'idle'\r\nORDER BY duration_seconds DESC\r\nLIMIT 5;\r\n"
    }
   ]
  }
 ]
}