# Use a base image with Prometheus pre-installed
FROM prom/prometheus:v2.32.1

# Copy your Prometheus configuration file
COPY prometheus.yml /etc/prometheus/prometheus.yml

# Expose port for Prometheus
EXPOSE 9090


